version: "3.0"

networks:
  henrik-net:

services:
  henrik_nginx:
#    entrypoint: ["echo", "Service NGINX disabled"]
    container_name: henrik_nginx
    build:
      context: "."
      dockerfile: "./nginx/Dockerfile"
    restart: "on-failure"
    ports:
      - "80:80"
    volumes:
      - ./nginx/henrik.conf:/etc/nginx/conf.d/henrik.conf
    network_mode: "host"

  henrik_db:
    container_name: henrik_db
    image: postgres
    restart: "on-failure"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ycps_db2
      - POSTGRES_PASSWORD=ycps_pass
      - POSTGRES_USER=ycps_user
